title: Blog
description: Reflections on Java and backend development, testability and maintainable design.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://elinazoldnere.github.io
